#!/bin/bash

# Keep this path for calling _common.sh inside the execution's context of backup and restore scripts
source ../settings/scripts/_common.sh
source /usr/share/yunohost/helpers

ynh_print_info "Declaring files to be backed up..."

#=================================================
# BACKUP THE APP MAIN DIR
#=================================================

ynh_backup "/etc/hostapd/$app/hostapd.conf" || true
ynh_backup "/etc/dnsmasq.$app/dhcpdv6.conf" || true
ynh_backup "/etc/dnsmasq.$app/dhcpdv4.conf" || true
ynh_backup "/etc/dnsmasq.d/$app.conf" || true

ynh_backup "/usr/local/bin/$service_name"

ynh_backup "/etc/openvpn/scripts/route-up.d/90-$service_name"
ynh_backup "/etc/openvpn/scripts/route-down.d/90-$service_name"

ynh_backup "/etc/systemd/system/$service_name.service"
ynh_backup "/etc/systemd/system/hostapd@$app.service"

#=================================================
# END OF SCRIPT
#=================================================

ynh_print_info "Backup script completed for $app. (YunoHost will then actually copy those files to the archive)."
