#!/bin/bash

# Wifi Hotspot app for YunoHost 
# Copyright (C) 2015 Julien Vaubourg <julien@vaubourg.com>
# Contribute at https://github.com/labriqueinternet/hotspot_ynh
# 
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
# 
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

# Retrieve arguments
domain=$(sudo yunohost app setting hotspot domain)

# The End
sudo systemctl stop ynh-hotspot
sudo systemctl disable ynh-hotspot
sudo yunohost service remove ynh-hotspot
sudo rm -f /etc/systemd/system/ynh-hotspot.service /usr/local/bin/ynh-hotspot
sudo rm -f /tmp/.ynh-hotspot-*

# Update firewall for DHCP
sudo yunohost firewall disallow --ipv6 UDP 547
sudo yunohost firewall disallow UDP 67

# Remove confs
sudo rm -fr /etc/dnsmasq.dhcpd/
sudo rm -f /etc/hostapd/hostapd.conf{.tpl?,}
sudo rm -f /etc/nginx/conf.d/${domain}.d/wifiadmin.conf
sudo rm -f /etc/php5/fpm/pool.d/wifiadmin.conf

# Remove free firmwares
if ! dpkg -l firmware-atheros &> /dev/null; then
  sudo rm -f /lib/firmware/htc_7010.fw
  sudo rm -f /lib/firmware/htc_9271.fw
fi

# Restart services
sudo systemctl restart php5-fpm
sudo systemctl reload nginx

# Remove sources
sudo rm -rf /var/www/wifiadmin/

exit 0
