#!/bin/bash

gitcommit=$(sudo yunohost app setting hotspot gitcommit)
tmpdir=$(mktemp -dp /tmp/ hotspot-restore-XXXXX)

git clone https://github.com/labriqueinternet/hotspot_ynh.git "${tmpdir}/"
git --work-tree "${tmpdir}/" --git-dir "${tmpdir}/.git/" reset --hard "${gitcommit}"

cd "${tmpdir}/scripts/"
./upgrade 

sudo rm -r "${tmpdir}/"

exit 0
