#!/bin/bash

ynh_setting() {
  app=${1}
  setting=${2}

  sudo grep "^${setting}:" "/etc/yunohost/apps/${app}/settings.yml" | sed s/^[^:]\\+:\\s*[\"\']\\?// | sed s/\\s*[\"\']\$//
}

domain=$(ynh_setting hotspot domain)
path=$(ynh_setting hotspot path)
wifi_ssid=$(ynh_setting hotspot wifi_ssid)
wifi_passphrase=$(ynh_setting hotspot wifi_passphrase)

if dpkg -l firmware-linux-nonfree &> /dev/null; then
  firmware_nonfree=yes
else
  firmware_nonfree=no
fi

export HOTSPOT_UPGRADE=1
sudo bash /etc/yunohost/apps/hotspot/scripts/remove
bash ./install "${domain}" "${path}" "${wifi_ssid}" "${wifi_passphrase}" "${firmware_nonfree}"

# Changes

if [ "$(ynh_setting hotspot ip6_firewall)" == '' ]; then
  multissid=$(ynh_setting hotspot multissid)
  ip6_firewall=$(printf '1|%.0s' $(seq "${multissid}"))
  ip6_firewall=$(echo "${ip6_firewall%?}")

  sudo yunohost app setting hotspot ip6_firewall -v "${ip6_firewall}"
fi

sudo systemctl start ynh-hotspot

exit 0
